version: '3.4'
services:
  lab_3_redocly:
    image: redocly/redoc
    ports:
      - "5006:80"
    volumes:
      - ./openapi.json:/usr/share/nginx/html/openapi.json:ro
    environment:
      - SPEC_URL=openapi.json